# Generated by Django 5.1.15 on 2026-09-22 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('resumes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SAVED', 'Saved'), ('READY', 'Ready to Apply'), ('REVIEW_REQUIRED', 'Review Required'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('FAILED', 'Failed'), ('WITHDRAWN', 'Withdrawn'), ('REJECTED', 'Rejected'), ('INTERVIEW', 'Interview')], db_index=True, default='SAVED', max_length=30)),
                ('automation_status', models.CharField(choices=[('IDLE', 'Idle / Manual'), ('QUEUED', 'Queued in Celery'), ('FORM_DETECTED', 'Form Detected'), ('FIELDS_FILLED', 'Fields Filled'), ('WAITING_REVIEW', 'Waiting For User Review'), ('SUBMIT_CONFIRMED', 'Submission Confirmed'), ('ERROR', 'Error Encountered')], default='IDLE', max_length=30)),
                ('application_url', models.URLField(blank=True, max_length=1000)),
                ('notes', models.TextField(blank=True, help_text='Personal interview notes, follow-up dates, etc.')),
                ('answers', models.JSONField(blank=True, default=dict, help_text='Key-value pairs of form questions and answered values')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('resume', models.ForeignKey(blank=True, help_text='Resume customized or selected for this job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='resumes.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'job'), name='unique_user_job_application')],
            },
        ),
    ]
