# Generated by Django 5.1.15 on 2026-09-22 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='detected_questions',
            field=models.JSONField(blank=True, default=list, help_text='Questions detected that require human input or verification'),
        ),
        migrations.AddField(
            model_name='application',
            name='error_message',
            field=models.TextField(blank=True, help_text='Detailed error explanation if automation fails'),
        ),
        migrations.AddField(
            model_name='application',
            name='filled_fields',
            field=models.JSONField(blank=True, default=dict, help_text='Fields that were successfully mapped and auto-filled'),
        ),
        migrations.AddField(
            model_name='application',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when final submission occurred', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='automation_status',
            field=models.CharField(choices=[('IDLE', 'Idle / Manual'), ('QUEUED', 'Queued'), ('STARTING_BROWSER', 'Starting Browser'), ('OPENING_JOB', 'Opening Job Page'), ('APPLICATION_DETECTED', 'Application Detected'), ('FILLING_FORM', 'Filling Form'), ('WAITING_FOR_REVIEW', 'Waiting For User Review'), ('SUBMITTING', 'Submitting Application'), ('SUBMITTED', 'Submitted'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='IDLE', max_length=30),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('SAVED', 'Saved'), ('READY', 'Ready to Apply'), ('QUEUED', 'Queued'), ('IN_PROGRESS', 'In Progress'), ('REVIEW_REQUIRED', 'Review Required'), ('SUBMITTED', 'Submitted'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('WITHDRAWN', 'Withdrawn'), ('INTERVIEW', 'Interview'), ('REJECTED', 'Rejected')], db_index=True, default='SAVED', max_length=30),
        ),
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('SUCCESS', 'Success')], default='INFO', max_length=20)),
                ('action', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_logs', to='applications.application')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
