# Generated by Django 5.1.15 on 2026-09-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('company', models.CharField(db_index=True, max_length=255)),
                ('location', models.CharField(blank=True, default='Not specified', max_length=255)),
                ('work_mode', models.CharField(choices=[('REMOTE', 'Remote'), ('HYBRID', 'Hybrid'), ('ON_SITE', 'On-site')], default='REMOTE', max_length=20)),
                ('description', models.TextField(help_text='Full job description')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_currency', models.CharField(default='USD', max_length=10)),
                ('salary_text', models.CharField(blank=True, help_text='Raw or formatted salary string', max_length=150)),
                ('experience_required_years', models.DecimalField(decimal_places=1, default=0.0, help_text='Minimum required experience in years', max_digits=4)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated required skills, e.g. Python, Django, PostgreSQL, Docker')),
                ('source', models.CharField(choices=[('LINKEDIN', 'LinkedIn'), ('INDEED', 'Indeed'), ('NAUKRI', 'Naukri'), ('WELLFOUND', 'Wellfound'), ('MANUAL', 'Manual Entry'), ('OTHER', 'Other Source')], default='MANUAL', max_length=30)),
                ('external_url', models.URLField(blank=True, max_length=1000)),
                ('normalized_url', models.CharField(blank=True, db_index=True, max_length=500)),
                ('external_job_id', models.CharField(blank=True, db_index=True, max_length=150)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('discovered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-discovered_at'],
                'indexes': [models.Index(fields=['company', 'title'], name='jobs_job_company_06c07c_idx'), models.Index(fields=['source', 'status'], name='jobs_job_source_2691b0_idx')],
            },
        ),
    ]
