# Generated by Django 5.1.15 on 2026-09-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary_currency',
            field=models.CharField(blank=True, default='USD', max_length=10),
        ),
    ]
