# Generated by Django 5.1.15 on 2026-09-22 09:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_salary_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_saved', models.BooleanField(db_index=True, default=False)),
                ('is_ignored', models.BooleanField(db_index=True, default=False)),
                ('match_score', models.IntegerField(db_index=True, default=0)),
                ('match_reasons', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_job_company_06c07c_idx',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_job_source_2691b0_idx',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='company',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='experience_required_years',
            new_name='experience_min',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='external_job_id',
            new_name='source_job_id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='status',
        ),
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('INTERNSHIP', 'Internship'), ('TRAINEE', 'Trainee'), ('TEMPORARY', 'Temporary'), ('UNKNOWN', 'Unknown')], db_index=True, default='FULL_TIME', max_length=30),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_max',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Maximum required experience in years', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='posted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.TextField(blank=True, default='', help_text='Specific job requirements and qualifications'),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=models.TextField(blank=True, default='', help_text='Key day-to-day responsibilities'),
        ),
        migrations.AddField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, db_index=True, default='Not specified', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.TextField(blank=True, default='', help_text='Comma-separated required skills, e.g. Python, Django, PostgreSQL, Docker'),
        ),
        migrations.AlterField(
            model_name='job',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('LINKEDIN', 'LinkedIn'), ('NAUKRI', 'Naukri'), ('INDEED', 'Indeed'), ('WELLFOUND', 'Wellfound'), ('OTHER', 'Other')], db_index=True, default='MANUAL', max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_mode',
            field=models.CharField(choices=[('REMOTE', 'Remote'), ('HYBRID', 'Hybrid'), ('ONSITE', 'Onsite'), ('UNKNOWN', 'Unknown')], db_index=True, default='REMOTE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['company_name', 'title'], name='jobs_job_company_07dd72_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['source', 'is_active'], name='jobs_job_source_51a596_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['posted_at'], name='jobs_job_posted__7edcdf_idx'),
        ),
        migrations.AddField(
            model_name='userjob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_jobs', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='userjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userjob',
            index=models.Index(fields=['user', 'is_saved'], name='jobs_userjo_user_id_a8320c_idx'),
        ),
        migrations.AddIndex(
            model_name='userjob',
            index=models.Index(fields=['user', 'is_ignored'], name='jobs_userjo_user_id_aa1485_idx'),
        ),
        migrations.AddIndex(
            model_name='userjob',
            index=models.Index(fields=['user', 'match_score'], name='jobs_userjo_user_id_3fe886_idx'),
        ),
        migrations.AddConstraint(
            model_name='userjob',
            constraint=models.UniqueConstraint(fields=('user', 'job'), name='unique_user_job'),
        ),
    ]
