# Generated by Django 5.1.15 on 2026-09-23 04:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_userjob_remove_job_jobs_job_company_06c07c_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=50)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('jobs_found', models.PositiveIntegerField(default=0)),
                ('jobs_new', models.PositiveIntegerField(default=0)),
                ('jobs_updated', models.PositiveIntegerField(default=0)),
                ('jobs_duplicate', models.PositiveIntegerField(default=0)),
                ('jobs_rejected', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial')], db_index=True, default='RUNNING', max_length=20)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='category_confidence',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='job',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='job',
            name='country',
            field=models.CharField(db_index=True, default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='first_seen_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='job',
            name='is_india',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_remote',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='job_category',
            field=models.CharField(choices=[('DATA_ENGINEERING', 'Data Engineering'), ('DATA_ANALYTICS', 'Data Analytics'), ('DATA_SCIENCE', 'Data Science'), ('MACHINE_LEARNING', 'Machine Learning / AI'), ('BI', 'Business Intelligence'), ('DATABASE', 'Database / SQL'), ('OTHER', 'Other')], db_index=True, default='DATA_ENGINEERING', max_length=30),
        ),
        migrations.AddField(
            model_name='job',
            name='location_type',
            field=models.CharField(choices=[('INDIA_CITY', 'India City'), ('INDIA_MULTI_CITY', 'India Multi-City'), ('REMOTE_INDIA', 'Remote India'), ('REMOTE_GLOBAL', 'Remote Worldwide'), ('OUTSIDE_INDIA', 'Outside India'), ('UNKNOWN', 'Unknown')], db_index=True, default='INDIA_CITY', max_length=30),
        ),
        migrations.AddField(
            model_name='job',
            name='matched_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='source_urls',
            field=models.JSONField(blank=True, default=list, help_text='All discovered source URLs'),
        ),
        migrations.AlterField(
            model_name='job',
            name='last_seen_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_currency',
            field=models.CharField(blank=True, default='INR', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.TextField(blank=True, default='', help_text='Comma-separated required skills, e.g. Python, SQL, Spark, Databricks'),
        ),
        migrations.AlterField(
            model_name='job',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('LINKEDIN', 'LinkedIn'), ('NAUKRI', 'Naukri'), ('INDEED', 'Indeed'), ('FOUNDIT', 'Foundit'), ('INTERNSHALA', 'Internshala'), ('WELLFOUND', 'Wellfound'), ('CUTSHORT', 'Cutshort'), ('INSTAHYRE', 'Instahyre'), ('OTHER', 'Other')], db_index=True, default='MANUAL', max_length=30),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['job_category', 'is_active'], name='jobs_job_job_cat_f29725_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_india', 'is_remote'], name='jobs_job_is_indi_fd9846_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['location_type'], name='jobs_job_locatio_e9364c_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['content_hash'], name='jobs_job_content_2268d3_idx'),
        ),
        migrations.AddIndex(
            model_name='jobsynclog',
            index=models.Index(fields=['source', 'status'], name='jobs_jobsyn_source_162e82_idx'),
        ),
        migrations.AddIndex(
            model_name='jobsynclog',
            index=models.Index(fields=['started_at'], name='jobs_jobsyn_started_205751_idx'),
        ),
    ]
