# Generated by Django 5.1.15 on 2026-09-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobsynclog_job_category_confidence_job_content_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_category',
            field=models.CharField(choices=[('DATA_ENGINEERING', 'Data Engineering'), ('DATA_ANALYTICS', 'Data Analytics'), ('DATA_SCIENCE', 'Data Science'), ('MACHINE_LEARNING', 'Machine Learning / AI'), ('BI', 'Business Intelligence'), ('DATABASE', 'Database / SQL'), ('SOFTWARE_ENGINEERING', 'Software Engineering'), ('CLOUD_DEVOPS', 'Cloud & DevOps'), ('OTHER', 'Other')], db_index=True, default='DATA_ENGINEERING', max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('LINKEDIN', 'LinkedIn'), ('NAUKRI', 'Naukri'), ('INDEED', 'Indeed'), ('FOUNDIT', 'Foundit'), ('INTERNSHALA', 'Internshala'), ('WELLFOUND', 'Wellfound'), ('CUTSHORT', 'Cutshort'), ('INSTAHYRE', 'Instahyre'), ('REMOTIVE', 'Remotive'), ('ARBEITNOW', 'Arbeitnow'), ('OTHER', 'Other')], db_index=True, default='MANUAL', max_length=30),
        ),
    ]
