# Generated by Django 5.1.15 on 2026-09-22 05:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Senior Python Developer Resume', max_length=200)),
                ('file', models.FileField(help_text='Upload your resume in PDF format only.', upload_to='resumes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('version', models.CharField(default='1.0', help_text='e.g. v1, 2026.1', max_length=50)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('is_default', models.BooleanField(default=False, help_text='Mark as default resume for automated match and application')),
                ('extracted_text', models.TextField(blank=True, help_text='Extracted plain text for search and automated matching')),
                ('file_size_kb', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-upload_date'],
            },
        ),
    ]
