# Generated by Django 5.1.15 on 2026-09-22 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('current_location', models.CharField(blank=True, help_text='e.g. Bengaluru, India', max_length=150)),
                ('preferred_locations', models.CharField(blank=True, help_text='Comma-separated locations, e.g. Bengaluru, Hyderabad, Remote', max_length=300)),
                ('work_authorization', models.CharField(blank=True, help_text='e.g. Authorized to work in India / US Citizen / Work Permit', max_length=200)),
                ('years_of_experience', models.DecimalField(decimal_places=1, default=0.0, help_text='Total professional experience in years', max_digits=4)),
                ('notice_period_days', models.PositiveIntegerField(default=30, help_text='Notice period in days (0 for immediate joiner)')),
                ('preferred_job_titles', models.CharField(blank=True, help_text='Target job titles, e.g. Python Developer, Django Engineer, Full Stack Lead', max_length=300)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated list of skills, e.g. Python, Django, PostgreSQL, Docker, Redis, Celery')),
                ('education', models.TextField(blank=True, help_text='Educational background, e.g. B.Tech in Computer Science, University of Technology (2020)')),
                ('certifications', models.TextField(blank=True, help_text='Certifications, e.g. AWS Certified Developer, CKA')),
                ('linkedin_url', models.URLField(blank=True, max_length=300)),
                ('github_url', models.URLField(blank=True, max_length=300)),
                ('portfolio_url', models.URLField(blank=True, max_length=300)),
                ('preferred_salary_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum expected annual compensation', max_digits=12, null=True)),
                ('preferred_salary_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum expected annual compensation', max_digits=12, null=True)),
                ('salary_currency', models.CharField(default='USD', max_length=10)),
                ('work_preference', models.CharField(choices=[('REMOTE', 'Remote'), ('HYBRID', 'Hybrid'), ('OFFICE', 'Work From Office'), ('FLEXIBLE', 'Any / Flexible')], default='FLEXIBLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
