# Generated by Django 5.1.15 on 2026-09-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contract_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience_level',
            field=models.CharField(choices=[('ALL', 'All Experience Levels'), ('FRESHER', 'Fresher / Entry (0-1 yrs)'), ('JUNIOR', 'Junior (1-3 yrs)'), ('MID', 'Mid-Level (3-5 yrs)'), ('SENIOR', 'Senior (5-8 yrs)'), ('LEAD', 'Lead / Staff (8+ yrs)')], default='ALL', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_time_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='internship_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='min_match_score',
            field=models.PositiveIntegerField(default=70, help_text='Minimum match score threshold (percentage)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='remote_only',
            field=models.BooleanField(default=False, help_text='Only show fully remote opportunities'),
        ),
        migrations.AddField(
            model_name='profile',
            name='target_roles',
            field=models.TextField(blank=True, default='Data Engineer, Junior Data Engineer, Data Analyst, Data Scientist, Machine Learning Engineer', help_text='Target roles to aggregate and prioritize'),
        ),
        migrations.AddField(
            model_name='profile',
            name='trainee_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='salary_currency',
            field=models.CharField(default='INR', max_length=10),
        ),
    ]
